version: '3.8'
services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: gwgvg_clickhouse
    restart: unless-stopped
    environment:
      - CLICKHOUSE_DB=gwarchivist
      - CLICKHOUSE_USER=dev
      - CLICKHOUSE_PASSWORD=dev
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro